/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'secondary-container': '#86f2e4',
        'surface-dim': '#d8dadc',
        'on-secondary': '#ffffff',
        'background': '#f7f9fb',
        'on-primary-fixed-variant': '#005321',
        'on-tertiary-fixed-variant': '#7f2a21',
        'primary': '#006e2f',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed': '#002109',
        'on-tertiary-fixed': '#410001',
        'primary-container': '#22c55e',
        'surface-tint': '#006e2f',
        'secondary-fixed': '#89f5e7',
        'surface-container-highest': '#e0e3e5',
        'outline': '#6d7b6c',
        'on-tertiary': '#ffffff',
        'inverse-on-surface': '#eff1f3',
        'tertiary-fixed-dim': '#ffb4a9',
        'surface-container': '#eceef0',
        'on-secondary-fixed': '#00201d',
        'tertiary-container': '#ff8b7c',
        'on-secondary-container': '#006f66',
        'surface-container-high': '#e6e8ea',
        'primary-fixed': '#6bff8f',
        'on-background': '#191c1e',
        'inverse-surface': '#2d3133',
        'outline-variant': '#bccbb9',
        'tertiary-fixed': '#ffdad5',
        'on-surface-variant': '#3d4a3d',
        'secondary-fixed-dim': '#6bd8cb',
        'surface-bright': '#f7f9fb',
        'primary-fixed-dim': '#4ae176',
        'on-primary': '#ffffff',
        'surface': '#f7f9fb',
        'on-error': '#ffffff',
        'tertiary': '#9e4036',
        'on-surface': '#191c1e',
        'inverse-primary': '#4ae176',
        'on-primary-container': '#004b1e',
        'on-tertiary-container': '#76231b',
        'secondary': '#006a61',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'surface-container-low': '#f2f4f6',
        'on-error-container': '#93000a',
        'surface-variant': '#e0e3e5',
        'on-secondary-fixed-variant': '#005049',
      },
      fontFamily: {
        'headline': ['var(--font-manrope)', 'Manrope', 'sans-serif'],
        'body': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'label': ['var(--font-inter)', 'Inter', 'sans-serif'],
      },
      borderRadius: {
        'DEFAULT': '1rem',
        'lg': '2rem',
        'xl': '3rem',
      },
    },
  },
  plugins: [],
};
